# Generated by Django 5.2.5 on 2025-09-03 17:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_request', models.CharField(choices=[('url', 'URL'), ('text', 'Text')], db_index=True, max_length=10)),
                ('instruction', models.TextField(blank=True, null=True)),
                ('raw_content', models.TextField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='articles_ar_created_187809_idx'), models.Index(fields=['input_request'], name='articles_ar_input_r_ef28d2_idx'), models.Index(fields=['content_hash'], name='articles_ar_content_93ec27_idx'), models.Index(fields=['input_request', 'created_at'], name='articles_ar_input_r_a9d871_idx')],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headline', models.CharField(max_length=500)),
                ('project_details', models.TextField()),
                ('participants', models.TextField(blank=True, null=True)),
                ('lots', models.TextField(blank=True, null=True)),
                ('organizations', models.TextField(blank=True, null=True)),
                ('is_final', models.BooleanField(db_index=True, default=False)),
                ('final_render', models.TextField()),
                ('generation_time', models.FloatField(default=0.0)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('pass', 'Pass'), ('fail', 'Fail'), ('partial', 'Partial')], db_index=True, default='pending', max_length=50)),
                ('validation_message', models.TextField(blank=True, null=True)),
                ('article_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.articlerequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UrlCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(db_index=True, unique=True)),
                ('url_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('cleaned_text', models.TextField()),
                ('status', models.CharField(default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['url_hash'], name='articles_ur_url_has_fff40d_idx'), models.Index(fields=['created_at'], name='articles_ur_created_fc6218_idx'), models.Index(fields=['expires_at'], name='articles_ur_expires_b454ca_idx'), models.Index(fields=['last_accessed'], name='articles_ur_last_ac_b51f13_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArticleHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('action_type', models.CharField(default='created', max_length=50)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='articles.article')),
                ('article_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='articles.articlerequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='articles_ar_created_5af482_idx'), models.Index(fields=['article'], name='articles_ar_article_a6beb7_idx'), models.Index(fields=['article_request'], name='articles_ar_article_7cf820_idx'), models.Index(fields=['action_type'], name='articles_ar_action__3f096e_idx'), models.Index(fields=['article', 'created_at'], name='articles_ar_article_d2bd2c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['created_at'], name='articles_ar_created_b5cc75_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_final'], name='articles_ar_is_fina_681641_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['validation_status'], name='articles_ar_validat_346486_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['article_request'], name='articles_ar_article_3a4b87_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_final', 'created_at'], name='articles_ar_is_fina_bf46b3_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['validation_status', 'created_at'], name='articles_ar_validat_9ee939_idx'),
        ),
    ]
